version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=true
    volumes:
      - .:/app
      - /app/__pycache__
    command: python app.py
    ports:
      - "5000:5000"

  # Simplified services for development
  redis:
    ports:
      - "6379:6379"

  db:
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=flask_app_dev
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=dev_password

# Remove production services for development
  nginx: null
  prometheus: null
  grafana: null
